### ISSUE TITLE
Support for Docker Compose file v3 ('createComposeFile' task)

### ISSUE THREAD

**Issue by joasilva** [chrisgahlert/gradle-dcompose-plugin#10]
Hi Chris!

I've been using your great Dcompose plugin to automate the building of Docker images, as well as the generation of docker-compose.yml files (y).

Regarding the latest, I have a use case for generating them in the latest "v3" format (https://docs.docker.com/compose/compose-file/), which is the deployment of service stacks to Docker Swarm Mode (https://docs.docker.com/engine/swarm/services/).

So, my question is: how can I use Dcompose to generate v3 docker-compose.yml files with the 'createComposeFile' task? Or is this a new feature? :-)

Cheers,

João

**Comment by chrisgahlert** [comment]
Hi João,

that would be a new feature. :)

I'll get on it in the next couple of days!

Cheers,
Chris

**Comment by joasilva** [comment]
BTW Chris,  maybe this can be of help to you?

https://github.com/aanand/docker.github.io/blob/8524552f99e5b58452fcb1403e1c273385988b71/compose/compose-file.md#upgrading

Cheers,

João

**Comment by chrisgahlert** [comment]
Starting with version 0.9.0 the plugin will generate version 3 Compose files by default. 

I didn't have the time to add all Swarm specific properties, but you can still modify the Compose file before it is written:
```
createComposeFile {
    version = '3' // default
    beforeSave { config ->
        config.services.myService.deploy.resources.reservations.memory = '60M'

        config.services.each { name, serviceConfig ->
            serviceConfig.deploy.mode = 'replicated'
            serviceConfig.deploy.replicas = 6
        }
    }
}
```

Kind regards,
Chris

**Comment by joasilva** [comment]
Great work, thanks :+1: 

But please update Dcompose 0.9.0 in Gradle Plugins as well (cf: https://plugins.gradle.org/plugin/com.chrisgahlert.gradle-dcompose-plugin):


FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/test-dcompose/build.gradle' line: 2

* What went wrong:
Plugin [id: 'com.chrisgahlert.gradle-dcompose-plugin', version: '0.9.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (plugin 'com.chrisgahlert.gradle-dcompose-plugin' has no version '0.9.0' - see https://plugins.gradle.org/plugin/com.chrisgahlert.gradle-dcompose-plugin for available versions)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by chrisgahlert** [comment]
Sorry, there was a problem with the release build and I didn't notice it. Should be available now.
