### ISSUE TITLE
Create compose file from subprojects

### ISSUE THREAD

**Issue by blankdots** [chrisgahlert/gradle-dcompose-plugin#11]
Thank you for the awesome plugin, been using it quite frequently.
I have a question (maybe feature request) regarding creating a single compose file from multiple subprojects. As it is easier to exemplify here it goes:
I have this project structure:
```
.
├── subproject1
│   ├── build.gradle
│   ├── Dockerfile
│   └── README.md
├── build.gradle
├── common.gradle
├── subproject2
│   ├── build.gradle
│   ├── Dockerfile
│   ├── nginx.conf
│   ├── README.md
│   └── web
│       ├── index.html
│       └── style.css
├── README.md
└── settings.gradle
```

In each of the subprojects as well as the root project, in build.gradle file there is something like (number of dockerfiles might vary):
```
dcompose {
    createComposeFile.useTags = true
    version = '3' // default - also supports '2'
    networks {
        prodEnv
    }
    registry ("$registryURL") {
    // Needs no user/pass
        }
    subproject1 {
        baseDir = file('.')
        repository = "${imageRepo}:${imageRepoPort}/image-name:latest"
        portBindings = ['8080:8080']
        binds = ['/data/subproject1:/data/subproject1']
        networks = [prodEnv]
    }
}
```
Now when I do `gradle CreateComposeFile` it creates a compose file for each subproject and that is an expected behaviour (because there is a need to run those services separately), but at the same time i want a single `docker-compose` file which includes all subprojects composefiles.

Is there an way to do that, might have missed something in the documentation? Or I might miss something to do this easier, or if this could be a feature it would be much appreciated.

**Comment by chrisgahlert** [comment]
Hi, thank you very much for your interest. 

I'm sorry I'm only responding now... I have been pretty busy the last couple of days.

Regarding your problem:
The main reason that compose files spanning multiple subprojects are not officially supported is that there might be name clashes in containers, networks or volumes. E.g. each subproject has a network named "default". When the network is created during a test run it will be created with the name "dcompose_\<Sha1-Hash of the subproject dir\>_default". This prevents name clashes when multiple subprojects use the same network name. When this network is added to a compose file it will be added with the name "default". Thus there might be "collisions" when multiple subprojects use the same name. The same applies for containers and volumes.

# Solution 1
I modify the createComposeFile task to also include the hashes to avoid name collisions. For backwards compatibility it might look like this:

```gradle
createComposeFile {
  includeSubprojects = true
}
```

I'll think I'll try to make an implementation for this in the next couple of days.

# Solution 2
As long as you make sure that the network-, container- and volume-names are unique, you should be able to use the current task to achieve what you are looking for:

```gradle
rootProject.createComposeFile.services = [
  dcompose.service(':subproject-a:myService1'),
  dcompose.service(':subproject-b:myService2')
]

project(':subproject-a') {
  dcompose {
    networks {
      subnetwork1
    }
    myService1 {
        image = '...'
        networks = [subnetwork1]
    }
}

project(':subproject-b') {
  dcompose {
    networks {
      subnetwork2
    }
    myService2 {
        image = '...'
        networks = [subnetwork2]
    }
}
```

This would give you a single compose file where each network is isolated from the rest.

If you want all containers to be in the same network:


```gradle
rootProject.createComposeFile.services = [
  dcompose.service(':subproject-a:myService1'),
  dcompose.service(':subproject-b:myService2')
]

dcompose {
  networks {
    // "default" is created by default 
  }
}

project(':subproject-a') {
  dcompose {
    myService1 {
        image = '...'
        networks = [network(':default')]
    }
}

project(':subproject-b') {
  dcompose {
    myService2 {
        image = '...'
        networks = [network(':default')]
    }
}
```

Just make sure that there are no name collisions and you should be fine.

Btw: It's also possible to create an additional composeFileTask:

```gradle
task createRootComposeFile(type: com.chrisgahlert.gradledcomposeplugin.tasks.DcomposeComposeFileTask) {
  services = [dcompose.service(':subproject-a:myService1'), dcompose.service(':subproject-b:myService2')]
}
```

I hope that these two solutions solve your current problem. I'll get back to you as soon as I have a working implementation for "Solution 1". 

Kind regards, 
Chris

**Comment by chrisgahlert** [comment]
P.S.
I think it is a bad idea to define the `baseDir = file('.')` as the Docker build root as this will include the generated `build/` directory as well. You should consider moving your Dockerfiles to a subdirectory like `src/main/docker`. ;)

**Comment by blankdots** [comment]
@chrisgahlert thanks for solutions both look really good, however I haven't got the chance to try out solution 2 but I will do so. I assume for the second part of solution 2 I can have any name of the network besides `default` ? Also I have pretty much control over the project so the names can be unique.

I also took into consideration your last comment.

**Comment by chrisgahlert** [comment]
The name is not important. When a compose file is generated, all services and there connected resources (dependent services, mounted volumes, connected networks) will be put in a compose file. If two services use two different instances of a network named default (e.g. because one service is connected to network `:subproject-a:default` and another service is connected to network `:subproject-b:default`) might cause problems.

So if you want all services to be able to talk to each other, than you should connect those services to the same network (e.g. the default network defined in the rootProject: `dcompose.network(':default')`).
If you want all services to be in separate networks than define a new network (not named default) in each subproject and connect the services to this network.
