### ISSUE TITLE
Gradle 4.0 support?

### ISSUE THREAD

**Issue by blankdots** [chrisgahlert/gradle-dcompose-plugin#12]
Been trying to run the same projects I have set up dcompose in with Gradle 4.0 and the following error keeps popping up:
```
FAILURE: Build failed with an exception.

* What went wrong:
Docker command failed: An attempt was made to execute build operations inside of a resource lock transform.  Aborting to avoid a deadlock.
> An attempt was made to execute build operations inside of a resource lock transform.  Aborting to avoid a deadlock.
```

Everything works fine in Gradle 3.5

**Comment by chrisgahlert** [comment]
Quick workaround:

Include this in your `build.gradle`:
```gradle
allprojects { prj ->
    prj.tasks.withType(com.chrisgahlert.gradledcomposeplugin.tasks.AbstractDcomposeTask) { task ->
        task.dockerClassLoaderFactory.getDefaultInstance()
    }
}
```

I'll be releasing a new version soon... and thanks for reporting! ;)

**Comment by chrisgahlert** [comment]
Fixed in new version 0.9.1 available now.

**Comment by phauer** [comment]
Thank you for fixing this so fast!

**Comment by blankdots** [comment]
@chrisgahlert Thank you!

Just a question regarding `DcomposeCopyFileFromContainerTask` as I noticed that with the new version i am having trouble copying the files (works in Gradle 3.5 with the new version of the plugin, files are copied). So does this look like a bug or I am doing something wrong (e.g. use `Sync` ?) or missing something (some changes in Gradle 4.0) ?

Error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tests:copyReportFiles'.
> Docker command failed: Could not find the file /tmp/build/reports/tests in container dcompose_4164440d_test

```
The source:

```
task copyReportFiles(type: DcomposeCopyFileFromContainerTask) {
    service = dcompose.test
    containerPath = '/tmp/build/reports/tests'
    destinationDir = file("build/reports/")
    cleanDestinationDir = false
}

startTestContainer.finalizedBy copyReportFiles
```
If necessary I can provide the full Gradle file.

**Comment by chrisgahlert** [comment]
I don't think this is related to the plugin itself:

The `DcomposeCopyFileFromContainerTask` can copy files from containers - whether they are running or not (i.e. they might have never been started). The task only has a dependency on the `create<Service>Container` task. 

For this reason I'm suspecting that you always copied the files from a container, where the `startTestContainer` task was previously executed causing the missing files to exist.

So in your example you would need to do the following:
1. Add a dependency to the start task:
```gradle
task copyReportFiles(type: DcomposeCopyFileFromContainerTask) {
    service = dcompose.test
    ...
    dependsOn startTestContainer // or more generic: "$service.projectPath:$service.startContainerTaskName"
}
```

2. In order to wait for the container to finish it's task, I would recommend to add the following properties:
```gradle
dcompose {
  test {
    // image,baseDir,command = ...
   
    waitForCommand = true // makes sure that the process will finish before moving to the copy task
    attachStdout = true // helpful for debugging: will be piped to System.out by default
    attachStderr = true // helpful for debugging: will be piped to System.err by default
  }
}
```

**Comment by blankdots** [comment]
@chrisgahlert Thank you!!
Point 2 was already satisfied, also included point 1.

I was able to pinpoint the issue to how those tests reports were generated (or more precisely were not generated); I was not really happy with that env in the first place, so this gave me a good reason to change it.
