### ISSUE TITLE
No setter for field "image" in DefaultService

### ISSUE THREAD

**Issue by DavidHamm** [chrisgahlert/gradle-dcompose-plugin#13]
https://github.com/chrisgahlert/gradle-dcompose-plugin/blob/e8bb72cd6de67acdfe21db4802dc12824539e04d/src/main/groovy/com/chrisgahlert/gradledcomposeplugin/extension/DefaultService.groovy#L35

there is no setter for the field "image" in DefaultService.

this works with groovy but in case you are using gradle-script-kotlin, there is no way to set the image.

**Comment by chrisgahlert** [comment]
Hi, thanks for reporting this. 

It has been fixed in version **0.9.2** available now.

Kind regards,
Chris
