### ISSUE TITLE
Update default version of docker-java

### ISSUE THREAD

**Issue by sfitts** [chrisgahlert/gradle-dcompose-plugin#14]
The current default has a bug in it relating to the parsing of docker's config.json file (when that file contains a cred store).  See https://github.com/docker-java/docker-java/issues/806 for more details.

**Comment by chrisgahlert** [comment]
Thanks for reporting this!

Fixed in new version **0.9.3** available now.

**Comment by sfitts** [comment]
Thanks for the quick turn around
