### ISSUE TITLE
Honor Dockerfile healthchek

### ISSUE THREAD

**Issue by jimmypoms** [chrisgahlert/gradle-dcompose-plugin#16]
It would be nice if the plugin would honor the Dockerfile healthcheck instruction (https://docs.docker.com/engine/reference/builder/#healthcheck) before continuing.

Amazing work by the way ;)

**Comment by chrisgahlert** [comment]
I'm sorry for the late response, but I completely overlooked this issue.

Great idea, I'll try to incorporate this in the next couple of days!

**Comment by chrisgahlert** [comment]
Feature is now included in version `0.11.0` available now!
