### ISSUE TITLE
Would like to apply multiple tags to the same image

### ISSUE THREAD

**Issue by sfitts** [chrisgahlert/gradle-dcompose-plugin#18]
It is pretty common when creating an image to give it more than one tag.  For example tagging both with the version (possibly both with and without the patch level) and with `latest`.  I'd like to do that for an image we describe in dcompose, but AFAICT each image is only given a single tag (based on the setting of the `repository` property).

Assuming I didn't miss something it would be nice to add a service property such as `tags` which would be a list of tags to apply when creating an image from the service.

**Comment by chrisgahlert** [comment]
Great idea imho!

I added this feature in version `0.12.0` available now. (See the release notes on how to use it!)

**Comment by sfitts** [comment]
Cool -- thanks.
