### ISSUE TITLE
Add "setter" for command property to ServiceReference

### ISSUE THREAD

**Issue by sfitts** [chrisgahlert/gradle-dcompose-plugin#19]
We have a use case where we create tasks which use a service that runs commands.  To make this work we need to modify the command attribute of the service as part of the task definition.  Currently we're using this:

```
compose {
    helm {
        image = 'vantiq/helm-kubectl:2.9.1'
        binds = [ volume("${project.clusterConfig}").bind('/root') ]
        waitForCommand = true
        attachStdout = true
    }
}

task helmVersion {
    doFirst {
        dcompose.findByName('helm').command = ['/usr/local/bin/helm', "version", '--short']
    }
    finalizedBy 'startHelmContainer'
}

task helmLs {
    doFirst {
        dcompose.findByName('helm').command = ['/usr/local/bin/helm', "ls"]
    }
    finalizedBy 'startHelmContainer'
}
```

However, this uses the deprecated `findByName` method to get the actual service.  It would be better to use the `service` method, but currently we can't since the resulting `ServiceReference` doesn't have a setter for `command`.

**Comment by chrisgahlert** [comment]
Hi, sorry for the late response - been busy the last couple of weeks.

Regarding your problem: If you want to keep doing the same thing, I'd recommend to replace the `dcompose.findByName('helm')` with `dcompose.services.getByName('helm')`. (The `dcompose.services`-property is an instance of `org.gradle.api.NamedDomainObjectContainer` which provides multiple methods like get/findByName, ...)

Another possibility would be to use two distinct containers for this:
```gradle
dcompose {
  helmLs {
    image = 'vantiq/helm-kubectl:2.9.1'
    binds = [ volume("${project.clusterConfig}").bind('/root') ]
    waitForCommand = true
    attachStdout = true
    command = ['/usr/local/bin/helm', "version", '--short']
  }
  helmVersion {
    image = helmLs.image
    binds = helmLs.binds
    waitForCommand = true
    attachStdout = true
    command = ['/usr/local/bin/helm', "ls"]
  } 
}

task helmVersion {
    dependsOn 'startHelmVersionContainer'
}

task helmLs {
    dependsOn 'startHelmLsContainer'
}
```

The `ServiceReference` interface is mainly just providing getters and are meant to be implemented by someone. 

Hope this solves your problem! :)

Kind regards,
Chris

**Comment by sfitts** [comment]
Yep, that does the trick.  Missed using the `services` container for this.

FWIW, I ended up going a different route and created a generic task that can "exec" a service (basically strings together container create, start w/ wait, container remove).  The implementation of that task still needs the find, so this is very helpful.
