### ISSUE TITLE
update docker-java to latest 3.0.0-RC5

### ISSUE THREAD

**Issue by jurisz** [chrisgahlert/gradle-dcompose-plugin#2]
Hi
Can you please update plugin to use latest docker-java:3.0.0-RC5

This should fix a bug:
https://github.com/docker-java/docker-java/issues/538
due to this one of our jenkins servers can't communicate with docker daemon

**Comment by chrisgahlert** [comment]
Hi, 
this issue is fixed in the latest version 0.3.2 available now.

**Comment by jurisz** [comment]
Hi

About networks.
By default dcompose creates new network, or connects to existing into multi
project setup, but each build always are going to create new docker
network.
This caused troubles in our jenkins builds as there are parallel branches
build simultaneously of same code base.
and we had 'can't create network errors, because of overlapping ip address
range'

But I found workaround:
connect to default 'bridge' and do not create any new
'dcompose_xxx_default_xxx' network

so what I did

dcompose {
networks.clear()
....
database {
baseDir = file('../../support/sql')
portBindings = ['5432']
networkMode = 'bridge'
}
}

May be someone else can find this useful and you can add this to wiki docs.

Thanks for nice plugin
Cheers
Juris

**Comment by chrisgahlert** [comment]
Hi Juris,

thanks for your info. I just created a new wiki page about all CI issues that I'm aware of:
https://github.com/chrisgahlert/gradle-dcompose-plugin/wiki/12.-CI-considerations

Could you please send me more info about the the problem you described, if the wiki page doesn't solve your problem.

Cheers, 
Chris

**Comment by jurisz** [comment]
Thanks
yes new page have similar solution to my one.
namely point 3 in "Network IP ranges"
Best
Juris

**Comment by chrisgahlert** [comment]
Glad I could help... :)
