### ISSUE TITLE
Converting complete image ref (including tag) to lower case prevents use of mixed case tags.

### ISSUE THREAD

**Issue by sfitts** [chrisgahlert/gradle-dcompose-plugin#22]
While docker registry and repository names must be lower case, image tags are case sensitive.  We have a need to publish tags that match existing images where upper case letters are used (see for example [jboss/keycloak](https://hub.docker.com/r/jboss/keycloak/)).

In the current code there are a few places that convert the image ref string to lower case *after* the tag is added, thus making it impossible for us to match the case as we would like.

I think the easiest way to address this will be to do the conversion to lower case in either the `ImageRef.parse` method or in the `ImageRef` constructor.  At these points the tag is separated from the other parts and so it is possible to avoid changing its case.  Later, when dealing with the entire reference string, that becomes much more difficult.

**Comment by chrisgahlert** [comment]
Thanks, I wasn't aware of that at the time of writing this code.

The issue will be fixed in version `v0.13.1`!

Kind regards
