### ISSUE TITLE
pull image progress

### ISSUE THREAD

**Issue by yunipingan** [chrisgahlert/gradle-dcompose-plugin#23]
Do you know how to get the progress when pulling image

**Comment by chrisgahlert** [comment]
I'm afraid this is not possible using this plugin. 

Internally the plugin communicates with the Docker Daemon through the REST API using the [docker-java](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/jaxrs/PullImageCmdExec.java) library. (I.e. it is not using the docker cli tools that would normally view the progress while pulling.) 

This means that we make a call to pull the image and only get a response, after the image was successfully downloaded.

If you still want this to happen, you should open up a feature request within the [docker-java](https://github.com/docker-java/docker-java/issues) library and I would implement the progress view afterwards.
