### ISSUE TITLE
Unable to force deletion of an image

### ISSUE THREAD

**Issue by henrik242** [chrisgahlert/gradle-dcompose-plugin#33]
I try to remove my `postgres` image using `removePostgresImage`, but I get:

```
> Docker command failed: conflict: unable to remove repository reference "postgres:10-alpine" (must force) - container e9945b2f7f89 is using its referenced image 5232c1629c4d
```

Setting `force = true` isn't possible:
```
val removePostgresImage by tasks.getting(com.chrisgahlert.gradledcomposeplugin.tasks.image.DcomposeImageRemoveTask::class) {
                force = true
}
```

``` 
Line 155:                 force = true
                            ^ Val cannot be reassigned

```

**Comment by henrik242** [comment]
Hmm, seems like I can work around it using:
```
val removePostgresContainer by tasks.getting
val removePostgresImage by tasks.getting {
    dependsOn(removePostgresContainer)
}
```

**Comment by chrisgahlert** [comment]
Hi,

by default the task `removePostgresContainer` should already have a dependency on `removePostgresImage`. (See bottom of table at https://github.com/chrisgahlert/gradle-dcompose-plugin/wiki/03.-Gradle-tasks#container-tasks). 

The main problem is, that the `force` flag is not intended to be set on the task, but the container instead:

```gradle
docmpose {
  postgres {
    ...
    forceRemoveImage = true // this is where you want to set it
  }
}

removePostgresImage {
  // This is not possible and will produce the error above:
  // force = true
}
// sorry for my lack of kotlin syntax ;)
```
(Documentation: https://github.com/chrisgahlert/gradle-dcompose-plugin/wiki/02.-List-of-service-properties#build-image-properties)

Kind regards,
Chris

**Comment by chrisgahlert** [comment]
Can this issue be closed?

**Comment by henrik242** [comment]
This really comes back to https://github.com/chrisgahlert/gradle-dcompose-plugin/issues/32.  We haven't been able to solve it properly.  I don't know if it can be solved, but we're working around it with `docker rmi` from the command line, so it's not a big problem.

**Comment by chrisgahlert** [comment]
Have you tried setting `dcompose.postgres.forceRemoveImage = true`? What is the output if you call `removePostgresImage`?

**Comment by henrik242** [comment]
Sorry, I haven't had the time to look into this.  I believe I have tried setting that, but I'll have set up a project where I can reproduce this again. Right now we're just using a `docker rmi` workaround and code that copes with pre-existing data in the postgres image.

**Comment by henrik242** [comment]
I have since switched to a different plugin, so I won't be able to work on this.  Closing for now, feel free to re-open if needed.
