### ISSUE TITLE
Getting logs from container build

### ISSUE THREAD

**Issue by GeorgHoffmeyer** [chrisgahlert/gradle-dcompose-plugin#35]
Is there a way to get the output gernerated by the createContainer Task (i.e. output from `docker build`) wirte to a file?

**Comment by chrisgahlert** [comment]
Hi Georg,

long time no see! ;)

I just added support to pass the build logs to the Gradle logger. See the release notes of the version `0.17.0` for usage details. 

I hope this solves your problem.

Kind regards,
Chris

**Comment by GeorgHoffmeyer** [comment]
Thanks for the fast response. The output look realy good. An additional feature might be to pipe to log to a defined file, that could be usefull on CI/CD pipelines with running gradle parallel.
But for my case this is working.
Are you still at EnBW?

Kind regards,
Georg

**Comment by chrisgahlert** [comment]
I also just added the logging to file feature in version `0.17.1`. 

Yes, still am at EnBW! :)
