### ISSUE TITLE
Group names for service tasks display as a closure reference

### ISSUE THREAD

**Issue by sfitts** [chrisgahlert/gradle-dcompose-plugin#4]
When I do `gradle tasks` I get a bunch of task entries like this:

```
Com.chrisgahlert.gradledcomposeplugin.DcomposePlugin$_updateTaskGroups_closure4$_closure12@2c80b0c8 tasks
---------------------------------------------------------------------------------------------------------
removeMongodbContainer
```

I think this is due to the task group property being assigned a cluster and not its result.  I'm running Gradle 3.1.

**Comment by chrisgahlert** [comment]
Hi, thank you very much for reporting this. I was not aware of it.
