### ISSUE TITLE
Allow setting restart policy for a container

### ISSUE THREAD

**Issue by sfitts** [chrisgahlert/gradle-dcompose-plugin#5]
This is the one thing missing as I look at moving from the bmuschko plug-in to this one (which I very much like BTW).

**Comment by chrisgahlert** [comment]
Thank you. I hope it suits your needs. And please keep reporting issues! ;)

The restart policy was added and will be available with version 0.5.4!

**Comment by chrisgahlert** [comment]
FYI: Version 0.5.4 is available now!
