### ISSUE TITLE
Add support for "top level" volumes

### ISSUE THREAD

**Issue by sfitts** [chrisgahlert/gradle-dcompose-plugin#6]
Unless I'm missing something (which I easily could be), I don't see a way to create top level volumes (e.g. those created by the `docker volume create` command).  Is that something you are considering adding?

**Comment by chrisgahlert** [comment]
It is already on my TODO list... you can expect something in 1-2 weeks :)

**Comment by chrisgahlert** [comment]
Sorry for keeping you waiting so long... this feature is now included in version 0.8.0! ;)

**Comment by sfitts** [comment]
NP, thanks!
