### ISSUE TITLE
Would like the ability to override default docker prefix.

### ISSUE THREAD

**Issue by sfitts** [chrisgahlert/gradle-dcompose-plugin#7]
I think that the only change needed is at line 44 in `DcompseExtension`.  If it were to pass the closure `{this.namePrefix}` instead of simply `{namePrefix}` then any changes to that property (which is read/write) would be seen.

Not sure if this would cause other issues, but from what I can see in the code, I don't think it would.  The unique prefix generated does prevent accidental collisions with other projects using the same names, but I don't think it is needed to do the up-to-date checks (again assume the artifact names are unique without the prefix).

Anyway, it would be a big help.

**Comment by chrisgahlert** [comment]
Hi, 

it should already be possible (that is the reason it is passed as a closure):

```
dcompose.namePrefix = 'myPrefix'
```

**Comment by chrisgahlert** [comment]
Oh... got it... that was working until I did some refactoring. I'll fix it!

**Comment by chrisgahlert** [comment]
Fixed in version 0.6.4
