### ISSUE TITLE
Generate docker-compose.yml usable by docker-compose

### ISSUE THREAD

**Issue by joasilva** [chrisgahlert/gradle-dcompose-plugin#9]
Hello Chris and kudos for the good work with the dcompose plugin!

Using the "createComposeFile" task, I'm able to create a docker-compose.yml file. However, the docker images referenced in docker-compose.yml files always have an hash string, for example "image: attxproject/uv-attx-dpus@sha256:d158441ae78993ce137f0ef82e6d41f504a0c66959f705b6aaa215d359ada2d9".

This makes it impossible to use the generated docker-compose.yml file with `docker-compose, as docker will evidently output the "ERROR: manifest unknown: manifest unknown" error, given that such image isn't either referenced in the local Docker registry or Docker Hub.

Is this a feature, or a bug? Please advise as it would be awesome to generate docker-compose.yml that could be used by docker-compose out-of-the-box.

Cheers,

João

**Comment by chrisgahlert** [comment]
Hi João,

thanks for the report. It's a bug! I'll look into that tonight...

**Comment by chrisgahlert** [comment]
As a temporary work-around you can set a property from a previous PR:

```gradle
createComposeFile.useAWSCompat = true
```

Then the image references in the compose file will use the tags instead of the image id.

**Comment by joasilva** [comment]
Thanks for the tip, Chris!

Using `createComposeFile.useAWSCompat = true`, I can generate a docker-compose.yml file with the images being referenced as "attxproject/uv-attx-dpus:latest", which is usable out-of-the-box by docker-compose :-)

Cheers,

João

**Comment by chrisgahlert** [comment]
This fix is included in the version **0.8.2** available now.

Thanks for your help and keep reporting! ;)

**Comment by joasilva** [comment]
My pleasure, please keep up the good work :-)
